/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guide',
    },
  ],
};

export default sidebars;
